---
# running all tests would take of the order of 1h
# there is currently a bug that results in the test failing
# https://bugs.launchpad.net/siesta/+bug/1725813
- name: run siesta tests
  shell: "make tests={{ item }} check"
  args:
    chdir: "{{ siesta_topdir }}/Obj/Tests"
    creates: "{{ siesta_topdir }}/Obj/Tests/{{ item }}/work"
  with_items: "{{ siesta_tests }}"

# fails (return code != 0), if "Test Failed." is found
# - name: check siesta test results
#   command: grep -vFxq "Test Failed." "{{ siesta_topdir }}/build/Testing/Temporary/LastTest.log"
